trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: ./templates/stage/deployment.yml
  parameters:
    ENV_SUFFIX: 'dev'
    BUILD_NUMBER: $(BUILD_NUMBER)
    AWS_CREDENTIALS: 'pipeline-1'
    DISPLAY_NAME: 'Dev Deployment'
